### ISSUE TITLE
Request for idea evaluation

### ISSUE THREAD

**Issue by fr4ncidir** [fr4ncidir/WoT_Ontology#1]
In Protégé si può aggiungere i namespaces necessari all'ontologia nel campo "ontology prefixes".

Si potrebbe, modificando il mio script tdbuilder.py automatizzare l'importazione dei namespaces nel jsap, come già facciamo per lo sparql.

Val la pena?

**Comment by lroffia** [comment]
Alcune considerazioni:

1) il JSAP potrebbe fare riferimento a più ontologie diverse e quindi in questo caso la parte di automatizzazione non credo servirebbe. Lo sviluppatore dovrebbe specificare comunque i namespaces che usa.

2) Non è detto che tutti i namespaces all’interno di un’ontologia vengano usati dal JSAP

Al momento lascerei la questione namespaces allo sviluppatore.

Forse però dovrei vedere prima il tool per capire meglio.

**Comment by lroffia** [comment]
Ho risposto
