### ISSUE TITLE
Potential problem with DELETE_EVENT

### ISSUE THREAD

**Issue by desmovalvo** [fr4ncidir/WoT_Ontology#7]
I think that simliar object may generate the same events, with different event instances. Let's say we have an event named wot:Ping, all the devices in a network may generate such an event by producing a custom instance. If you execute your DELETE_EVENT (that is supposed to delete events from a Thing), then you delete the global event, even if other Things use it.

**Comment by fr4ncidir** [comment]
Please check if with the new release this problem is fixed

**Comment by desmovalvo** [comment]
I guess you're referring to the file deletes/del_event_instance.sparql... If so, it should now be ok. Only rename the SPARQL Update, since it is currently named as DELETE_ACTION_INSTANCE

**Comment by fr4ncidir** [comment]
Done!
